DatingApp/Controllers/MatchesController.cs
using AutoMapper;
using DatingApp.DTOs;
using DatingApp.Helpers;
using DatingApp.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace DatingApp.Controllers
{
    public class MatchesController : BaseController
    {
        private readonly HttpClient _client;
        private readonly IMapper _mapper;

        public MatchesController(HttpClient client, IMapper mapper)
        {
            _client = client;
            _mapper = mapper;
        }
        #region Matches
        public async Task<IActionResult> Index()
        {
            if (!TryGetToken(out string token))
                return View("Error");

            _client.SetBearerToken(token);

            var response = await _client.GetAsync("AppUsers");
            if (response.IsSuccessStatusCode)
            {
                var paginationHeader = response.Headers.GetValues("Pagination").FirstOrDefault();
                var pagination = JsonConvert.DeserializeObject<_UserParams>(paginationHeader);

                var jsonString = await response.Content.ReadAsStringAsync();
                var appUsers = JsonConvert.DeserializeObject<List<MemberDTo>>(jsonString);

                var viewModel = new ViewModel
                {
                    Users = appUsers,
                    Pagination = pagination
                };
                return View(viewModel);
            }
            return View("Error");
        }


        public async Task<IActionResult> PartialView([FromBody] _UserParams userParams)
        {
            if (!TryGetToken(out string token))
                return View("Error");

            _client.SetBearerToken(token);

            var response = await _client.GetAsync($"AppUsers?pageNumber={userParams.pageNumber}&MinAge={userParams.MinAge}&MaxAge={userParams.MaxAge}&Gender={userParams.Gender}&OrderBy={userParams.OrderBy}");
            if (response.IsSuccessStatusCode)
            {
                var paginationHeader = response.Headers.GetValues("Pagination").FirstOrDefault();
                var pagination = JsonConvert.DeserializeObject<_UserParams>(paginationHeader);

                var jsonString = await response.Content.ReadAsStringAsync();
                var appUsers = JsonConvert.DeserializeObject<List<MemberDTo>>(jsonString);

                var viewModel = new ViewModel
                {
                    Users = appUsers,
                    Pagination = pagination
                };
                return PartialView("PartialView", viewModel);
            }
            return View("Error");
        }

        #endregion
        public async Task<IActionResult> UserDetails(string username)
        {
            if (!TryGetToken(out string token))
                return View("Error");

            _client.SetBearerToken(token);

            var response = await _client.GetAsync("AppUsers/" + username);
            if (response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var appUsers = JsonConvert.DeserializeObject<MemberDTo>(jsonString);
                var viewModel = new ViewModel
                {
                    member=appUsers
                };
                return View(viewModel);
            }


            return View("Error");

        }
        #region likes
        public async Task<ActionResult> AddLike(string UserName)
        {
            if (!TryGetToken(out string token))
                return View("Error");

            _client.SetBearerToken(token);

            var response = await _client.PostAsJsonAsync($"Likes/{UserName}", new { });

            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true, username = UserName });
            }
            else
            {
                var responseContent = await response.Content.ReadAsStringAsync();
                return Json(new { success = false, error = responseContent });
            }
        }
        #endregion
    }

}

DatingApp/Views/Matches/Index.cshtml
@model DatingApp.Models.ViewModel

<link href="~/cardview/cardview.css" rel="stylesheet" />
<script src="~/tabs/jquery.min.js"></script>
<script src="~/js/filter/filter.js"></script>

<div class="container">

    <div class="d-flex justify-content-center mt-1 mb-2">
        <form class="d-flex mt-3" autocomplete="off" id="Filter" onsubmit="filterclick(); return false;">
            <div class="d-flex mx-2">
                <label class="col-form-label-sm">Age from:</label>
                <input class="form-control ms-1" id="MinAge" name="MinAge" style="width:70px" type="number" value="@Model.Pagination.MinAge">
            </div>
            <div class="d-flex mx-2">
                <label class="col-form-label-sm">Age to:</label>
                <input class="form-control ms-1" id="MaxAge" name="MaxAge" style="width:70px" type="number" value="@Model.Pagination.MaxAge">
            </div>
            <div class="d-flex px-2">
                <label class="col-form-label-me-2">Gender:</label>
                <select class="form-select ms-1" id="Gender" name="Gender" style="width:130px">
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                </select>
            </div>
            <input type="hidden" id="OrderBy" name="OrderBy" />
            <button class="btn btn-primary ms-1" type="submit">Apply filter</button>
            <button class="btn btn-info ms-1" type="button" id="resetFilterButton">Reset filter</button>
            <button class="btn btn-primary ms-1" type="button" id="lastActiveButton">Last Active</button>
            <button class="btn btn-primary ms-1" type="button" id="createdButton">Created</button>
        </form>
    </div>
    <div id="results">
        <Partial name="PartialView" />
    </div>
   
</div>
<script type="text/javascript">
    $('#lastActiveButton').on('click', function () {
        $('#OrderBy').val('LastActive');
        filterclick();
    });

    $('#createdButton').on('click', function () {
        $('#OrderBy').val('Created');
        filterclick();
    });
    $('#resetFilterButton').on('click', function () {
        $('#MinAge').val('@Model.Pagination.MinAge');
        $('#MaxAge').val('@Model.Pagination.MaxAge');
        $('#Gender').val('@Model.Pagination.Gender');
        $('#OrderBy').val('');
        filterclick();
    });
</script>

DatingApp/Views/Matches/PartialView.cshtml
@model DatingApp.Models.ViewModel

<script src="~/js/filter/iconify.min.js"></script>
<link href="~/css/likesheader.css" rel="stylesheet" />
<div class="text-center mt-1">
    <h4 class="fst-italic mb-4">
        <span class="iconify" data-icon="mdi:heart-multiple" data-inline="false"></span>
        <b>Your Perfect Match  @Model.Pagination.TotalItems Awaits!</b>
        <span class="iconify" data-icon="mdi:heart-multiple" data-inline="false"></span>
    </h4>
</div>


<div class="row">

    <div class="d-flex justify-content-center">

        @foreach (var item in Model.Users)
        {
            <div class="col-md-2 mb-3">
                <div class="card">
                    <div class="card-img-wrapper">
                        <img src="@(item.PhotoUrl != null ? item.PhotoUrl : "/image/sample_user_icon.png")" alt="@item.KnownAs" class="card-img-top">

                        <ul class="list-inline member-icons animate text-center">
                            <li class="list-inline-item">
                                <a href="@Url.Action("UserDetails", "Matches", new { username = item.UserName })">
                                    <i class="fa fa-user fa-2x"></i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a class="like-button" data-username="@item.UserName">
                                    <i class="fa fa-heart fa-2x"></i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a class="message-button" data-username="@item.UserName">
                                    <i class="fa fa-envelope fa-2x"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="card-body p-1">
                        <h5 class="card-title text-center mb-1">
                            <i class="fa fa-user me-2"></i>
                            @item.KnownAs, @item.Age
                        </h5>
                        <p class="card-text card-muted text-center">@item.Country</p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@if (Model.Pagination != null)
{
    <div class="d-flex justify-content-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item @(Model.Pagination.CurrentPage == 1 ? "disabled" : "")">
                    <a class="page-link" href="#" onclick="loadPage(@(Model.Pagination.CurrentPage - 1))">Previous</a>
                </li>
                @for (var i = 1; i <= Model.Pagination.TotalPages; i++)
                {
                    <li class="page-item @(Model.Pagination.CurrentPage == i ? "active" : "")">
                        <a class="page-link" href="#" onclick="loadPage(@i)">@i</a>
                    </li>
                }
                <li class="page-item @(Model.Pagination.CurrentPage == Model.Pagination.TotalPages ? "disabled" : "")">
                    <a class="page-link" href="#" onclick="loadPage(@(Model.Pagination.CurrentPage + 1))">Next</a>
                </li>
            </ul>
        </nav>
    </div>
}
<script>
    function loadPage(page) {
        var jsonData = {
            MaxAge: $("#MaxAge").val(),
            MinAge: $("#MinAge").val(),
            Gender: $("#Gender").val(),
            OrderBy: $("#OrderBy").val(),
            pageNumber: page
        };

        $.ajax({
            type: 'POST',
            url: '/Matches/PartialView',
            data: JSON.stringify(jsonData),
            contentType: "application/json",
            success: function (response) {
                debugger
                $('#results').html(response);
            },
            error: function (xhr) {
                toastr.info(JSON.parse(xhr.responseText).error);
            }
        });
    }
</script>

<script type="text/javascript">
    $('.like-button').on('click', function (event) {
        event.preventDefault();
        var userName = $(this).data('username');
        
        $.ajax({
            url: '@Url.Action("AddLike", "Matches")' + '?UserName=' + encodeURIComponent(userName),
            type: 'POST',
            success: function (data) 
            {
                if (data.success) 
                {
                    toastr.success('you have liked ' + data.username);
                } else {
                    toastr.error(data.error);
                }
            },
            error: function (xhr, status, error) {
                toastr.error('Error adding like: ' + error);
            }
        });
    });

</script>
         
<script>
    $('.message-button').click(function () {
        var username = $(this).data('username');

        window.location.href = '/Matches/UserDetails?username=' + username + '&activetab=Messages';
    });
</script>


               

DatingApp/Views/Matches/UserDetails.cshtml
@using Humanizer

@using System.Globalization


@model DatingApp.Models.ViewModel
@{
    ViewData["Title"] = "UserDetails";
}
<script src="~/tabs/jquery.min.js"></script>

<link href="/tabs/detailstabs.css" rel="stylesheet" />
<script src="/tabs/detailstabs.js"></script>

<link href="~/tabs/gallerie/css/h-smart-thumbnail.css" rel="stylesheet" />
<script src="~/tabs/gallerie/js/h-smart-thumbnail.js"></script>
<script src="~/tabs/gallerie/js/h-smart-thumbnail.min.js"></script>




<div class="row mt-4">
    <div class="col-3">
        <div class="card">
            <img src="@(Model.member.Photos != null ? Model.member.PhotoUrl : "/image/sample_user_icon.png")" alt="@Model.member.KnownAs" class="card-img-top img-thumbnail" />
            <div class="card-body">
                <div>
                    <strong>Location:</strong>
                    <p>@Model.member.City, @Model.member.Country</p>
                </div>
                <div>
                    <strong>Age:</strong>
                    <p>@Model.member.Age</p>
                </div>
                <div>
                    <strong>Last Active:</strong>
                    @{
                        var timeDifference = DateTime.Now - Model.member.LastActive;
                        string formattedTime = timeDifference.Humanize();
                    }

                    <p>@formattedTime ago</p>
                </div>

                <div>
                    <strong>Member Since:</strong>
                    <p>@Model.member.Created.ToString("MM-yy-yyyy", CultureInfo.InvariantCulture)</p>
                </div>
            </div>
            <div class="card-footer">
                <div class="d-flex btn-group">
                    <button class="btn btn-primary">Like</button>
                    <button class="btn btn-success">Message</button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-8">

        <div class="tabs-container">
            <div class="tabs">
                <div class="tab active" data-tab="@Model.member.KnownAs">About @Model.member.KnownAs </div>
                <div class="tab" data-tab="Interests">Interests</div>
                <div class="tab" data-tab="Photo">Photos</div>
                <div class="tab" data-tab="Messages">Messages</div>

            </div>
            <div id="@Model.member.KnownAs" class="tabcontent active">
                <strong style="text-decoration:underline">
                    Description
                </strong>
                <p>@Model.member.Introduction</p>
                <strong style="text-decoration:underline">
                    Looking For</strong>
                <p>@Model.member.LookingFor</p>

            </div>
            <div id="Interests" class="tabcontent">
                <strong>Interests</strong>
                <p>@Model.member.Interests</p>
            </div>
            <div id="Photo" class="tabcontent">

                <div class="example">
                    <ul>
                        @foreach (var photo in Model.member.Photos)
                        {
                            <li>
                                <img src="@photo.Url">
                            </li>
                        }
                    </ul>
                </div>


            </div>
            <div id="Messages" class="tabcontent">
                <Partial name="PartialViewMessageThread" />
            </div>
        </div>
    </div>


    <!--  JS for Photo gallery -->
    <script>
        $('.example').hSmartThumbnail();
    </script>

    <!-- #endregion -->
    <!   Js for Message---->
    <script>
        $(document).ready(function () {
            $('.tabs .tab[data-tab="Messages"]').one('click', function () {
                var userName = "@Model.member.KnownAs";
                $.ajax({
                    url: '/Message/PartialViewMessageThread?userName=' + userName,
                    type: 'GET',
                    success: function (data) {
                        $('#Messages').html(data);
                    },
                    error: function (xhr, status, error) {
                        var errorMessage = xhr.responseText ? JSON.parse(xhr.responseText).error : 'Error loading messages';
                        toastr.info(errorMessage);
                    }
                });
            });
        });

    </script>

    <script>
        $(document).ready(function () {
            $('.btn.btn-success').click(function () {
                var userName = "@Model.member.KnownAs";

                $('.tabcontent').removeClass('active');
                $('.tab').removeClass('active');

                
                $('#Messages').addClass('active');
                $('.tab[data-tab="Messages"]').addClass('active');

               
                $.ajax({
                    url: '/Message/PartialViewMessageThread?userName=' + userName,
                    type: 'GET',
                    success: function (data) {
                        $('#Messages').html(data);
                    },
                    error: function (xhr, status, error) {
                        var errorMessage = xhr.responseText ? JSON.parse(xhr.responseText).error : 'Error loading messages';
                        toastr.info(errorMessage);
                    }
                });
            });
        });
    </script>


    <script>
        $(document).ready(function () {
            var urlParams = new URLSearchParams(window.location.search);
            var activeTab = urlParams.get('activetab');

            if (activeTab === 'Messages') {
                $('.tab').removeClass('active');
                $('.tabcontent').removeClass('active');
                $('[data-tab="Messages"]').addClass('active');
                $('#Messages').addClass('active');
                $('.tabs .tab[data-tab="Messages"]').click();
               
            }
        });
    </script>